  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>


<div class="row">

    <div class="col-sm">     
    </div>
  <div class='col-sm'>
  <form action="" method="post">
    <br>
    <br>
    <center>
    <img class="img-fluid" width="200" height="200" src="<?php echo $this->url->getBaseUri(); ?>public/img/profile.png" alt="">
    <br>
    <br>
    <link rel="stylesheet" type = "text/css" href="myStyle.css">
    <div class="form-group">
      <label>Email address</label>
      <!--div class="col-12 col-md-4 mb-4 mb-md-0"-->
        <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
      <!--/div-->
    </div>
    <div class="form-group">
      <label>Password</label>
      <!--div class="col-12 col-md-4 mb-4 mb-md-0"-->
        <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
      <!--/div-->
    </div>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
      <h1></h1>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
   
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form>
  </div>

    <div class="col-sm">     
    </div>
</div>