<div class="row">
    <div class="col-sm">     
    </div>
    <div class="col-sm">
      <form action="" method="post" >
      <input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">
      
      <center>
      <img class="img-fluid" width="200" height="200" src="<?php echo $this->url->getBaseUri(); ?>public/img/profile.png" alt="">
      <br>
      <br>
      
      <div class="form-group">
        <label>Email address</label>
        <input type="email" name="email" class="form-control" id="email" placeholder="Enter email"  required >
      </div>
      <div class="form-group">
        <label>Password</label>
        <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
      </div>
      <div class="form-group">
        <label>Firstname</label>
        <input type="text" name="firstname" class="form-control" id="firstname" placeholder="Firstname"  required  >
      </div> 
      
      <button type="submit" class="btn btn-info">Submit</button>
      
      <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>

      </form>
    </div>
    <div class="col-sm">     
    </div>
</div>