<div class="row">

    <div class="col-sm">
      <p align="right"><img src="<?php echo $this->url->getBaseUri().'public/img/aboutMe.jpg' ?>" height="200px" width="200px" class="img-thumbnail"></center></p>
    </div>
  <div class='col-sm'>
  <form action="" method="post">
    
    <font size = 20></font>
    <h>นายนรวร   โหราวรรณ์<br></h>
    <h>Noraworn Horawan<br></h>
    <h>590610631<br></h>
    <h>Faculty of Computer Engineering<br></h>
    <h>Chiang Mai  University<br></h>
    <br>
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form>
  </div>

</div>